### ISSUE TITLE
Договориться о стиле

### ISSUE THREAD

**Issue by jack-theripper** [myJetCats/react-project-kitchen-frontend#1]
Договориться о стиле комментариев: язык, префиксы, правила именования веток (лучше называть включая название задачи, не спринта); коммитов и пулл-реквестов

**Comment by jack-theripper** [comment]
Ну вот первая задача, которую можно начать обсуждать. 

Assignees - кто взял эту задачу в работу, либо кого назначили
Labels - метки, (например Bug - ошибка в коде) удобно использовать для поиска в фильтрах 
Projects - К какому проекту (на гитхабе) относится данный issue. Можно поменять прогресс сразу отсюда.
Milestone - контрольные точки для отслеживания pr и прогресса наверное использовать не будем
Development - отсылка на пул реквест
Notifications - справа вверху  есть колокольчик где видно все подвижки по этой задаче

Все в одном месте

**Comment by jack-theripper** [comment]
(для примера), предлагаю:

- при нахождении багов:

Создать новый Issue и прицепить его к проекту. Установить метку Bug. Когда ты смотришь этот Issue справа отображается "панелька".

**Comment by RayFreedom88** [comment]
Да, хорошая идея называть ветки по названию выполняемой задачи, плюсую! 

По поводу коммитов предлагаю использовать упрощенный вариант стандарта Conventional Commits:

```
feat: add hat wobble
^--^  ^------------^
|     |
|     +-> Краткое изложение в повелительном наклонении.
|
+------->  feat, fix, refactor.
```

_Пример:_
"commit: `feat: добавить компонент Head`",
"commit: `fix: поправить длину строки с ценой`"

**Почему краткое изложение в повелительном наклонении?**

Коммит это изменение кода, сообщение в коммите можно расценивать как инструкцию по изменению этого кода. Сделать, изменить, добавить, обновить, поправить? — всё это конкретные инструкции для разработчика.
Повелительное наклонение рекомендовано в самой системе версионирования [Git](https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches)
